mode: "hyper"

model:
  pretrained_path: "no"
  reduction: 4

dataset:
  path: "data/CARS"
  name: "CARS"
  train_classes: 98
  labeled_fraction: 1.0
  random_erasing: False

training:
  epochs: 70
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 10
  num_elements_class: 7
  temperature: 0.11
  loss: "ce_l2"
  ulb_batch_size_factor: 1
  ulb_loss_weight: 1
