mode: "hyper"

resnet:
  pretrained_path: "no"
  reduction: 4
  bottleneck: False

dataset:
  path: "data/CARS"
  name: "CARS"
  train_classes: 98
  labeled_fraction: 1.0
  random_erasing: False
  randaugment_num_ops: 2
  randaugment_magnitude: 9
  num_workers: 4

training:
  epochs: 70
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 10
  num_elements_class: 7
  temperature: 0.11
  loss_lb: "lsce"
  loss_ulb: ""
  ulb_batch_size_factor: 7
  ulb_loss_weight: 1
