dataset:
  path: "data/CARS"
  name: "CARS"
  train_classes: 98
  labeled_fraction: 1.0
  random_erasing: False

training:
  epochs: 2
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 10
  num_elements_class: 7
  temperatur: 0.11
