mode: "train"

resnet:
  pretrained_path: "no"
  reduction: 4
  bottleneck: False

dataset:
  path: "data/CUB"
  name: "CUB"
  train_classes: 100
  labeled_fraction: 0.1
  random_erasing: False
  randaugment_num_ops: 2
  randaugment_magnitude: 9

training:
  epochs: 1
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 6
  num_elements_class: 9
  temperature: 0.11
  loss_lb: "lsce"
  loss_ulb: ""
  ulb_batch_size_factor: 1
  ulb_loss_weight: 1
