mode: "train"

model:
  pretrained_path: "no"
  reduction: 4

dataset:
  path: "data/CUB"
  name: "CUB"
  train_classes: 100
  labeled_fraction: 0.1
  random_erasing: False

training:
  epochs: 1
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 6
  num_elements_class: 9
  temperature: 0.11
  loss: "ce_l2"
  ulb_batch_size_factor: 1
  ulb_loss_weight: 1
