mode: "train"

model:
  pretrained_path: "no"

dataset:
  path: "data/CUB"
  name: "CUB"
  train_classes: 100
  labeled_fraction: 0.1
  random_erasing: False

training:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 6
  num_elements_class: 9
  temperatur: 0.11
