mode: "train"

resnet:
  pretrained_path: "no"
  reduction: 4
  bottleneck: False

dataset:
  path: "data/CUB"
  name: "CUB"
  train_classes: 100
  labeled_fraction: 0.1
  transform_lb_strong: True
  transform_ulb_strong: "randaugment"
  random_erasing: False
  randaugment_num_ops: 2
  randaugment_magnitude: 9
  num_workers: 4

training:
  epochs: 1
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 6
  num_elements_class: 9
  loss_lb: "lsce"
  loss_lb_temp: 0.11
  loss_ulb: ""
  loss_ulb_weight: 1
  loss_ulb_warmup: 0
  loss_ulb_temp: 0.11
  loss_ulb_threshold: 0.8
  ulb_batch_size_factor: 7
