mode: "train"

resnet:
  pretrained_path: "no"
  reduction: 4
  bottleneck: False

dataset:
  path: "data/Stanford_Online_Products"
  name: "SOP"
  train_classes: 11318
  labeled_fraction: 0.1
  transform_ulb_strong: "randaugment"
  random_erasing: False
  randaugment_num_ops: 2
  randaugment_magnitude: 9
  num_workers: 4

training:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 15
  num_elements_class: 6
  temperature: 0.11
  loss_lb: "lsce"
  loss_ulb: ""
  loss_ulb_weight: 1
  loss_ulb_warmup: 0
  ulb_batch_size_factor: 7
