mode: "train"

model:
  pretrained_path: "no"
  reduction: 4

dataset:
  path: "data/Stanford_Online_Products"
  name: "SOP"
  train_classes: 11318
  labeled_fraction: 0.1
  random_erasing: False

training:
  epochs: 20
  lr: 0.0001
  weight_decay: 0.000006
  num_classes_iter: 15
  num_elements_class: 6
  temperature: 0.11
  loss: "ce_l2"
  ulb_batch_size_factor: 1
  ulb_loss_weight: 1
