mode: "test"

model: "backbone_gnn"

resnet:
  pretrained_path: "./results/SOP/2022-12-16_16:39:03/SOP_10.0_best.pth"
  reduction: 4
  bottleneck: False
  mixedpoolweight: 1.0

gnn:
  pretrained_path: "no"
  num_layers: 1
  num_heads: 1
  num_proxies: 11318
  add_mlp: False
  gnn_conv: "GAT"
  gnn_fc: False
  reduction_layer: False
  batch_proxies: False
  kclosest_edges: 20

dataset:
  path: "data/Stanford_Online_Products"
  name: "SOP"
  train_classes: 11318
  labeled_fraction: 0.1
  transform_lb_strong: False
  transform_ulb_strong: "randaugment"
  random_erasing: False
  randaugment_num_ops: 4
  randaugment_magnitude: 9
  num_workers: 4

training:
  epochs: 70
  lr: 0.00032866392149250967
  lr_gnn: 0.00032866392149250967
  weight_decay: 2.6448990400370304e-12
  num_classes_iter: 20
  num_elements_class: 3
  loss_lb: "ce"
  loss_lb_temp: 0.729014226278502
  loss_ulb: "ce_thresh"
  loss_ulb_weight: 5
  loss_ulb_warmup: 0
  loss_ulb_temp: 1
  loss_ulb_threshold: 0.9
  loss_ulb_gnn_threshold: 0.9
  loss_proxy: "l2"
  loss_proxy_weight: 1
  ulb_batch_size_factor: 7
